trigger:
  branches:
    include:
      - main

jobs:
  - job: Build
    displayName: Build and Publish Docker Image
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self

      - task: DockerInstaller@0
        displayName: 'Install Docker'

      - script: |
          docker build -t $(DOCKER_USERNAME)/counterapi:latest .
        displayName: 'Build Docker Image'

      - task: Docker@2
        displayName: 'Push Docker Image to Docker Hub'
        inputs:
          command: push
          containerRegistry: 'DockerHubServiceConnection' # Service Connection for Docker Hub
          repository: 'counterapi'
          tags: latest

