- name: Extract version info
  id: vars
  run: |
    echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
    echo "BRANCH_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

- name: Build and push Docker image
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: |
      yourdockerhubusername/your-image-name:${{ env.SHA_TAG }}
      yourdockerhubusername/your-image-name:${{ env.BRANCH_TAG }}
      yourdockerhubusername/your-image-name:latest
