name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in repo for debugging
      run: |
        ls -alh
        ls -alh src
        ls -alh tests

    - name: Verify Dockerfile location and content
      run: cat Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image (debug)
      run: |
        docker build --no-cache -t your-dockerhub-username/counterapi:latest .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .  # Ensure context is the root of the repo
        file: ./Dockerfile  # Correct path to the Dockerfile
        push: true  # Push the image
        tags: ${{ secrets.DOCKER_USERNAME }}/CounterApi:latest
