name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch (or change to your branch)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true  # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest  # Change 'your-image-name' to your image name
