name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in repo for debugging
      run: ls -alh  # Verifies that the file structure is correct

    - name: Verify Dockerfile location and content
      run: cat Dockerfile  # Prints out Dockerfile contents for verification

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Set to current directory where Dockerfile and code are located
        file: ./Dockerfile  # Ensure the correct Dockerfile path is used
        push: true  # Push image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/counterapi:latest  # Tag image with username and latest
